name: Báo cáo lỗi
about: Tạo một báo cáo lỗi để giúp chúng tôi cải thiện chất lượng dự án
title: "[Bug]: "
labels: "type: bug"
assignees: duythanhvn
issue_body: true
inputs:
- type: description
  attributes:
    value: Cảm ơn bạn đã dành thời gian báo cáo lỗi, lòng hoàn thiện biễu mẫu chi tiết dưới đây.
- type: input
  attributes:
    label: Đường dẫn đến nội dung có lỗi
    required: true
- type: dropdown
  attributes:
    label: Chọn nền tảng bạn đang gặp vấn đề
    choices:
      - macOS
      - Linux/Ubuntu/...
      - Windows
      - Apple iOS
      - Android
- type: input
  attributes:
    label: Nhập thông tin trình duyệt (browsers) của bạn
- type: textarea
  attributes:
    label: Thông tin thêm
    description: Vui lòng cung cấp thêm bất kỳ thông tin nào bạn tin là hữu ích cho chúng tôi, [như hình ảnh]..

