name: Bug Report
about: File a bug report
title: "[Bug]: "
labels: "bug, triage"
assignees: monalisa
issue_body: true
inputs:
- type: description
  attributes:
    value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
- type: input
  attributes:
    label: What version are you using?
    required: true
- type: dropdown
  attributes:
    label: How did you download the software?
    required: true
    choices:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
- type: textarea
  attributes:
    label: Expected Behavior
    description: What did you expect to happen?
    required: true
- type: textarea
  attributes:
    label: What actually happened?
    required: true
- type: multi_select
  attributes:
    label: What browsers are you seeing the problem on?
    choices:
    - Firefox
    - Chrome
    - Safari
    - Microsoft Edge
- type: checkboxes
  attributes: 
    label: Contributor Checklist
    description: Please verify that you've followed these steps
    choices:
      - label: I have read the Code of Conduct
        required: true
      - label: I have read the Contributing Guidelines
        required: true
